INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('metaData11', 'metaData22', 'metaData33', 1);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('metaData21', 'metaData22', 'metaData23', 2);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('metaData31', 'metaData32', 'metaData33', 3);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('test1', 'test2', 'test3', 5);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('test1', 'test2', 'test3', 6);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('test1', 'test2', 'test3', 7);
INSERT INTO PUBLIC.METADATA (META_DATA1, META_DATA2, META_DATA3, FILE_ID) VALUES ('test1', 'test2', 'test3', 8);